version: '3.8'

services:
  nt-cctv-api:
    build: .
    container_name: cctv-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Bangkok
    networks:
      - innovation_net

networks:
  innovation_net:
    external: true

